<?php
$b64 = file_get_contents('update_fixed_base64.txt');
$b64 = trim($b64);
$php = "<?php\n";
$php .= "\$zipB64 = '" . $b64 . "';\n";
$php .= "\$zipPath = __DIR__ . '/update_temp.zip';\n";
$php .= "\n\$laravelRoot = null;\n";
$php .= "if (isset(\$_POST['manual_path'])) {\n";
$php .= "    \$path = rtrim(\$_POST['manual_path'], '/\\\\');\n";
$php .= "    if (file_exists(\$path . '/artisan')) {\n";
$php .= "        \$laravelRoot = \$path;\n";
$php .= "    } else {\n";
$php .= "        \$error = \"File artisan tidak ditemukan di path: \" . htmlspecialchars(\$path);\n";
$php .= "    }\n";
$php .= "} else {\n";
$php .= "    // Auto detect\n";
$php .= "    \$possiblePaths = [\n";
$php .= "        __DIR__,\n";
$php .= "        dirname(__DIR__),\n";
$php .= "        dirname(dirname(__DIR__)),\n";
$php .= "        dirname(__DIR__) . '/jukungsync-v1',\n";
$php .= "        dirname(__DIR__) . '/jukungsync',\n";
$php .= "        dirname(__DIR__) . '/laravel',\n";
$php .= "        __DIR__ . '/jukungsync-v1',\n";
$php .= "        __DIR__ . '/jukungsync',\n";
$php .= "        __DIR__ . '/laravel'\n";
$php .= "    ];\n";
$php .= "    foreach(\$possiblePaths as \$path) {\n";
$php .= "        if(file_exists(\$path . '/artisan')) {\n";
$php .= "            \$laravelRoot = realpath(\$path);\n";
$php .= "            break;\n";
$php .= "        }\n";
$php .= "    }\n";
$php .= "}\n";
$php .= "\nif (!\$laravelRoot) {\n";
$php .= "    echo '<div style=\"font-family:sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; border: 1px solid #ccc; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">';\n";
$php .= "    echo '<h2 style=\"color:red;\">Pencarian Folder Gagal</h2>';\n";
$php .= "    echo '<p>Sistem tidak dapat mendeteksi lokasi folder aplikasi Laravel Anda secara otomatis.</p>';\n";
$php .= "    if (isset(\$error)) {\n";
$php .= "        echo '<p style=\"color:red; background: #ffebee; padding: 10px; border-radius: 4px;\"><b>Error:</b> ' . \$error . '</p>';\n";
$php .= "    }\n";
$php .= "    echo '<form method=\"POST\">';\n";
$php .= "    echo '<label style=\"font-weight: bold;\">Masukkan path/lokasi folder Laravel Anda secara manual:</label><br>';\n";
$php .= "    echo '<small style=\"color: #666;\">Folder ini adalah folder utama yang berisi file <code>artisan</code>. (Bisa dicari di File Manager Hostinger, biasanya di: <code>/home/u123456789/domains/ptutamamadaniraya.com/jukungsync-v1</code>)</small><br><br>';\n";
$php .= "    echo '<input type=\"text\" name=\"manual_path\" style=\"width: 100%; padding: 10px; border: 1px solid #aaa; border-radius: 4px; box-sizing: border-box;\" value=\"' . htmlspecialchars(dirname(__DIR__)) . '\" required><br><br>';\n";
$php .= "    echo '<button type=\"submit\" style=\"padding: 10px 20px; background: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; font-weight: bold;\">Lanjutkan Update</button>';\n";
$php .= "    echo '</form>';\n";
$php .= "    echo '</div>';\n";
$php .= "    exit;\n";
$php .= "}\n";
$php .= "\n// Proceed with extraction\n";
$php .= "file_put_contents(\$zipPath, base64_decode(\$zipB64));\n";
$php .= "\$zip = new ZipArchive;\n";
$php .= "if (\$zip->open(\$zipPath) === TRUE) {\n";
$php .= "    \$zip->extractTo(\$laravelRoot);\n";
$php .= "    \$zip->close();\n";
$php .= "    unlink(\$zipPath);\n";
$php .= "    unlink(__FILE__);\n";
$php .= "    \n";
$php .= "    // Attempt migration & clearing cache\n";
$php .= "    chdir(\$laravelRoot);\n";
$php .= "    exec('php artisan migrate --force 2>&1', \$output, \$return_var);\n";
$php .= "    exec('php artisan optimize:clear 2>&1');\n";
$php .= "    \n";
$php .= "    // Display success\n";
$php .= "    echo '<div style=\"font-family:sans-serif; max-width: 600px; margin: 50px auto; text-align: center; padding: 30px; border: 1px solid #ddd; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">';\n";
$php .= "    echo '<h1 style=\"color:green;\">✅ UPDATE BERHASIL!</h1>';\n";
$php .= "    echo '<p style=\"color: #555;\">File berhasil diekstrak dengan tepat ke folder:<br><code>' . htmlspecialchars(\$laravelRoot) . '</code></p>';\n";
$php .= "    echo '<div style=\"text-align: left; background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0; border: 1px solid #eee;\">';\n";
$php .= "    echo '<p style=\"font-weight: bold; margin-top: 0;\">Status Migrasi Database:</p>';\n";
$php .= "    echo '<pre style=\"margin: 0; white-space: pre-wrap; font-size: 13px; color: #333;\">' . implode(\"\\n\", \$output) . '</pre>';\n";
$php .= "    echo '</div>';\n";
$php .= "    echo '<p>Cache sistem telah dibersihkan. Fitur Pengaturan Landing Page sudah siap digunakan.</p><br>';\n";
$php .= "    echo '<a href=\"/\" style=\"display:inline-block; padding: 12px 24px; background: #fbbf24; color: #000; font-weight: bold; text-decoration: none; border-radius: 5px; margin-right: 10px;\">Kembali ke Beranda</a> ';\n";
$php .= "    echo '<a href=\"/dashboard\" style=\"display:inline-block; padding: 12px 24px; background: #1f2937; color: white; font-weight: bold; text-decoration: none; border-radius: 5px;\">Buka Dashboard</a>';\n";
$php .= "    echo '</div>';\n";
$php .= "    exit;\n";
$php .= "} else {\n";
$php .= "    echo 'Gagal mengekstrak file ZIP.';\n";
$php .= "}\n";
$php .= "?>";
$output = "# Script Installer Anti Gagal (Pendeteksi Folder Interaktif)\n\nSilakan copy semua kode di bawah ini, timpa file `update.php` Anda yang lama, lalu simpan.\n\n```php\n" . $php . "\n```\n";
file_put_contents('C:/Users/USER/.gemini/antigravity/brain/f12d4254-b154-471c-b76a-aa67f4e9fcf6/installer_artifact.md', $output);
?>
