<?php
$b64_migration = file_get_contents('payload_migration.txt');
$b64_model = file_get_contents('payload_customer_model.txt');
$b64_ctrl = file_get_contents('payload_customer_controller.txt');
$b64_inv_ctrl = file_get_contents('payload_invoice_ctrl.txt');
$b64_view_idx = file_get_contents('payload_customer_index.txt');
$b64_admin = file_get_contents('payload_admin_layout.txt');
$b64_inv_view_idx = file_get_contents('payload_index.txt');
$b64_inv_view_edit = file_get_contents('payload_edit_invoice.txt');

$php = "<?php\n\n";
$php .= "use Illuminate\\Support\\Facades\\Route;\n";
$php .= "use Illuminate\\Support\\Facades\\File;\n";
$php .= "use Illuminate\\Support\\Facades\\Artisan;\n\n";
$php .= "Route::get('/install-customer-master', function() {\n";
$php .= "    try {\n";
$php .= "        File::put(database_path('migrations/2026_06_10_070151_create_customers_table.php'), base64_decode('$b64_migration'));\n";
$php .= "        File::put(app_path('Models/Customer.php'), base64_decode('$b64_model'));\n";
$php .= "        File::put(app_path('Http/Controllers/CustomerController.php'), base64_decode('$b64_ctrl'));\n";
$php .= "        File::put(app_path('Http/Controllers/InvoiceController.php'), base64_decode('$b64_inv_ctrl'));\n";
$php .= "        if (!is_dir(resource_path('views/customers'))) mkdir(resource_path('views/customers'), 0755, true);\n";
$php .= "        File::put(resource_path('views/customers/index.blade.php'), base64_decode('$b64_view_idx'));\n";
$php .= "        File::put(resource_path('views/layouts/admin.blade.php'), base64_decode('$b64_admin'));\n";
$php .= "        File::put(resource_path('views/invoices/index.blade.php'), base64_decode('$b64_inv_view_idx'));\n";
$php .= "        File::put(resource_path('views/invoices/edit.blade.php'), base64_decode('$b64_inv_view_edit'));\n";
$php .= "        \n";
$php .= "        Artisan::call('migrate', ['--force' => true]);\n";
$php .= "        Artisan::call('view:clear');\n";
$php .= "        \n";
$php .= "        // Restore the original web.php safely\n";
$php .= "        \$web_php = <<<'EOD'\n";
$php .= file_get_contents('routes/web.php');
$php .= "\nEOD;\n";
$php .= "        File::put(base_path('routes/web.php'), \$web_php);\n";
$php .= "        return redirect('/customers')->with('success', 'Fitur Master Data Customer berhasil di-install dan terintegrasi otomatis dengan sistem Invoice!');\n";
$php .= "    } catch (\\Exception \$e) {\n";
$php .= "        return 'Error: ' . \$e->getMessage();\n";
$php .= "    }\n";
$php .= "});\n";

$md = "```php\n" . $php . "\n```";
file_put_contents('C:/Users/USER/.gemini/antigravity/brain/f12d4254-b154-471c-b76a-aa67f4e9fcf6/installer_customer_master.md', $md);
